gcp:
  projectId: ""
  gsaEmail: ""
  bucketName: ""

# Kubernetes Configuration
app:
  namespace: ""
  serviceAccountName: "app-ksa"

# Test Pod Configuration
testPod:
  name: "gcp-wi-test-pod"
  image: "python:3.11-slim"
  restartPolicy: "Never" 
